[program:baby_tracker]
directory=/srv/baby-tracker
command=/srv/baby-tracker/main.sh
stderr_logfile=/var/log/baby_tracker.err.log
stdout_logfile=/var/log/baby_tracker.out.log
stopsignal=INT
stopasgroup=true
killasgroup=true