[program:baby_tracker]
directory=/srv/baby-tracker
command=/srv/baby-tracker/main.sh
environment=DB_FILE="./db.sqlite",SLACK_OAUTH_TOKEN="xoxb-207850742689-2105858454273-3G8vI8KLvvIVuM8qXmYIJOWk",CHANNEL_ID="G01HEHBPUSK"
stderr_logfile=/var/log/baby_tracker.err.log
stdout_logfile=/var/log/baby_tracker.out.log
stopsignal=INT
stopasgroup=true
killasgroup=true
